Small fixes

diff --git a/doc/tests/run b/doc/tests/run
--- a/doc/tests/run
+++ b/doc/tests/run
@@ -1,12 +1,21 @@
-#!/bin/bash 
+#! /bin/sh 
+#
+#   AMQP conformance tests
+#
+#   This script runs the AMQP conformance tests.
 
-function die() { echo $@; exit -1; }
 
-if [ "x$IBASE" == "x" ]; then
+function die() {
+    echo "E: $@"
+    echo "I: aborting conformance tests"
+    exit -1
+}
+
+if [ "$IBASE" = "" ]; then
     die "IBASE not set"
 fi
 
-if [ "x$COLOR" == "xno" ]; then
+if [ "$COLOR" = "no" ]; then
     unset GREEN RED RESET
 else
     GREEN=$'\e[32;02m'
@@ -15,22 +24,20 @@ else
     RESET=$'\e[37;00m'
 fi
 
-
 if [ -e works.pal ] && [ -e fails.pal ]; then
     echo "initializing ..."
     if [ "works.pal" -nt "works" ]; then
         pal works.pal &>/dev/null
     fi
-    ./works &>/dev/null || die "the most simple working testcase did not return 0, exitting..."
+    ./works &>/dev/null || die "could not initialise (positive test failed)"
 
     if [ "fails.pal" -nt "fails" ]; then
         pal fails.pal &>/dev/null
     fi
-    ./fails &>/dev/null && die "the most simple failing testcase did not return != 0, exitting..."
+    ./fails &>/dev/null && die "could not initialise (negative test failed)"
 else
     echo "no works/fails pal scripts found... continuing w/o initial test"
 fi
-
 
 
 for testcase in `ls *.pal|grep -v amq_test_base.pal|grep -v works.pal|grep -v fails.pal`; do
